const apiCatalog = {
    project: 'Apex Group Of Schools CRM',
    audience: 'External mobile app developer',
    note: 'Use these backend APIs only. Mobile build artifacts are intentionally not kept in this repository.',
    baseUrlExamples: [
        'https://YOUR-DOMAIN.com/api',
        'https://YOUR-DOMAIN.com/api',
        'http://YOUR-SERVER-IP:3000/api',
        'http://localhost:3000/api'
    ],
    auth: {
        login: 'POST /api/login',
        header: 'Authorization: Bearer <token>',
        contentType: 'application/json'
    },
    endpoints: [
        { method: 'GET', path: '/api/health', auth: false, group: 'System', description: 'Server health check.' },
        { method: 'GET', path: '/api/ping', auth: false, group: 'System', description: 'Simple API ping.' },
        { method: 'POST', path: '/api/login', auth: false, group: 'Auth', description: 'Login for admin, principal, branch, student, teacher, and staff.' },
        { method: 'POST', path: '/api/session/heartbeat', auth: true, group: 'Auth', description: 'Keep logged-in session active.' },
        { method: 'POST', path: '/api/session/end', auth: true, group: 'Auth', description: 'Logout/end logged-in session. Mobile app should remove saved token after success.' },
        { method: 'POST', path: '/api/upload', auth: false, group: 'Files', description: 'Upload assignment, syllabus, profile, lecture, or message file. Accepts multipart/form-data file field or JSON dataUrl/base64 and returns file.url.' },

        { method: 'GET', path: '/api/student/me', auth: true, group: 'Student Portal', description: 'Current student profile.' },
        { method: 'GET', path: '/api/students', auth: false, group: 'Students', description: 'List students.' },
        { method: 'POST', path: '/api/students', auth: true, group: 'Students', description: 'Create or update students.' },
        { method: 'DELETE', path: '/api/students/:id', auth: true, group: 'Students', description: 'Delete student.' },
        { method: 'GET', path: '/api/student-attendance', auth: false, group: 'Student Portal', description: 'Student attendance records.' },
        { method: 'POST', path: '/api/student-attendance', auth: false, group: 'Student Portal', description: 'Save student attendance records.' },
        { method: 'GET', path: '/api/student-results', auth: false, group: 'Student Portal', description: 'Student exam results. Optional query: ?studentId=ID&classGrade=Class%205&examName=Mid%20Term&session=2026.' },
        { method: 'POST', path: '/api/student-results', auth: false, group: 'Student Portal', description: 'Save/publish student result.' },
        { method: 'GET', path: '/api/student-syllabus', auth: false, group: 'Student Portal', description: 'Student syllabus. Optional query: ?classGrade=Class%205&subject=English&term=Term%201&session=2026.' },
        { method: 'POST', path: '/api/student-syllabus', auth: false, group: 'Student Portal', description: 'Save/publish syllabus item.' },
        { method: 'GET', path: '/api/date-sheet', auth: false, group: 'Student Portal', description: 'Published exam date sheet.' },
        { method: 'POST', path: '/api/date-sheet', auth: false, group: 'Student Portal', description: 'Save/publish exam date sheet.' },
        { method: 'GET', path: '/api/student-assignments', auth: false, group: 'Student Portal', description: 'Student assignment submissions.' },
        { method: 'POST', path: '/api/student-assignments', auth: false, group: 'Student Portal', description: 'Submit assignment from mobile app.' },
        { method: 'GET', path: '/api/student-diary', auth: false, group: 'Student Portal', description: 'Class diary records.' },
        { method: 'POST', path: '/api/student-diary', auth: false, group: 'Student Portal', description: 'Save class diary record.' },
        { method: 'GET', path: '/api/student-courses', auth: false, group: 'Student Portal', description: 'Class courses/content.' },
        { method: 'POST', path: '/api/student-courses', auth: false, group: 'Student Portal', description: 'Save class course/content.' },
        { method: 'GET', path: '/api/uploaded-assignments', auth: false, group: 'Student Portal', description: 'School-uploaded assignments.' },
        { method: 'POST', path: '/api/uploaded-assignments', auth: false, group: 'Student Portal', description: 'Save school-uploaded assignment.' },
        { method: 'GET', path: '/api/uploaded-lectures', auth: false, group: 'Student Portal', description: 'Uploaded lecture files/links.' },
        { method: 'POST', path: '/api/uploaded-lectures', auth: false, group: 'Student Portal', description: 'Save uploaded lecture.' },
        { method: 'GET', path: '/api/student-quizzes', auth: false, group: 'Student Portal', description: 'Quizzes for student app.' },
        { method: 'POST', path: '/api/student-quizzes', auth: false, group: 'Student Portal', description: 'Save quiz.' },
        { method: 'GET', path: '/api/student-quiz-submissions', auth: false, group: 'Student Portal', description: 'Student quiz submissions.' },
        { method: 'POST', path: '/api/student-quiz-submissions', auth: false, group: 'Student Portal', description: 'Save quiz submission.' },
        { method: 'GET', path: '/api/about-software', auth: false, group: 'Student Portal', description: 'About software details for app info screen.' },

        { method: 'GET', path: '/api/teacher/me', auth: true, group: 'Teacher Portal', description: 'Current teacher profile.' },
        { method: 'GET', path: '/api/teachers', auth: false, group: 'Teachers', description: 'List teachers with timetable/schedule data.' },
        { method: 'POST', path: '/api/teachers', auth: true, group: 'Teachers', description: 'Create or update teachers.' },
        { method: 'DELETE', path: '/api/teachers/:id', auth: true, group: 'Teachers', description: 'Delete teacher.' },
        { method: 'GET', path: '/api/teacher-attendance', auth: false, group: 'Teacher Portal', description: 'Teacher attendance records.' },
        { method: 'POST', path: '/api/teacher-attendance', auth: false, group: 'Teacher Portal', description: 'Save teacher attendance records.' },
        { method: 'GET', path: '/api/teacher-salaries', auth: false, group: 'Teacher Portal', description: 'Teacher salary records.' },
        { method: 'POST', path: '/api/teacher-salaries', auth: false, group: 'Teacher Portal', description: 'Save teacher salary record.' },
        { method: 'GET', path: '/api/teacher-assigned-classes', auth: false, group: 'Teacher Portal', description: 'Assigned classes from teacher schedule and manual records. Optional query: ?teacherId=ID.' },
        { method: 'POST', path: '/api/teacher-assigned-classes', auth: false, group: 'Teacher Portal', description: 'Save manual assigned class record.' },

        { method: 'GET', path: '/api/fees/payments', auth: false, group: 'Fees', description: 'Fee payment history.' },
        { method: 'GET', path: '/api/fees/due-balances', auth: false, group: 'Fees', description: 'Fee due balances.' },
        { method: 'GET', path: '/api/fees', auth: false, group: 'Fees', description: 'Fee records.' },
        { method: 'POST', path: '/api/fees/manual-payment', auth: false, group: 'Fees', description: 'Save manual payment.' },
        { method: 'POST', path: '/api/fees/mark-unpaid', auth: false, group: 'Fees', description: 'Mark fee unpaid.' },
        { method: 'POST', path: '/api/fees/challan-token', auth: false, group: 'Fees', description: 'Create one QR challan token.' },
        { method: 'POST', path: '/api/fees/challan-tokens', auth: false, group: 'Fees', description: 'Create multiple QR challan tokens.' },
        { method: 'GET', path: '/api/fees/pay/:token', auth: false, group: 'Fees', description: 'Open/pay challan token.' },
        { method: 'GET', path: '/api/fees/fine-charge', auth: false, group: 'Fees', description: 'Fine charge list.' },
        { method: 'POST', path: '/api/fees/fine-charge', auth: false, group: 'Fees', description: 'Save fine charge.' },
        { method: 'GET', path: '/api/class-fees', auth: false, group: 'Fees', description: 'Class-wise fee setup.' },
        { method: 'POST', path: '/api/class-fees', auth: true, group: 'Fees', description: 'Save class-wise fee setup.' },

        { method: 'GET', path: '/api/messages', auth: true, group: 'Portal Communication', description: 'Messages for logged-in user or admin filter.' },
        { method: 'POST', path: '/api/messages', auth: true, group: 'Portal Communication', description: 'Send portal message from Admin/Principal to Student, Teacher, or Staff recipients.' },
        { method: 'GET', path: '/api/special-notices?portal=student', auth: false, group: 'Portal Communication', description: 'Student portal notices.' },
        { method: 'GET', path: '/api/special-notices?portal=teacher', auth: false, group: 'Portal Communication', description: 'Teacher portal notices.' },
        { method: 'POST', path: '/api/special-notices', auth: false, group: 'Portal Communication', description: 'Save/publish special notice.' },
        { method: 'DELETE', path: '/api/special-notices/:id', auth: false, group: 'Portal Communication', description: 'Delete notice.' },
        { method: 'GET', path: '/api/leave-requests', auth: false, group: 'Portal Communication', description: 'Leave requests. Optional query: ?role=Student or ?role=Teacher.' },
        { method: 'POST', path: '/api/leave-requests', auth: false, group: 'Portal Communication', description: 'Submit leave request.' },
        { method: 'POST', path: '/api/leave-requests/:id', auth: false, group: 'Portal Communication', description: 'Approve/reject/update leave request.' },
        { method: 'DELETE', path: '/api/leave-requests/:id', auth: false, group: 'Portal Communication', description: 'Delete leave request.' },
        { method: 'GET', path: '/api/complaints', auth: false, group: 'Portal Communication', description: 'Complaint list. Optional query: ?role=Student, ?role=Teacher, ?role=Family, ?senderId=ID, ?status=Pending.' },
        { method: 'POST', path: '/api/complaints', auth: false, group: 'Portal Communication', description: 'Submit student, teacher, or family complaint.' },
        { method: 'POST', path: '/api/complaints/:id', auth: false, group: 'Portal Communication', description: 'Update complaint status, reply, or action taken.' },
        { method: 'DELETE', path: '/api/complaints/:id', auth: false, group: 'Portal Communication', description: 'Delete complaint.' },

        { method: 'GET', path: '/api/branches', auth: false, group: 'Admin Setup', description: 'List branches.' },
        { method: 'POST', path: '/api/branches', auth: false, group: 'Admin Setup', description: 'Create/update branch.' },
        { method: 'DELETE', path: '/api/branches/:id', auth: false, group: 'Admin Setup', description: 'Delete branch.' },
        { method: 'GET', path: '/api/staff', auth: false, group: 'Admin Setup', description: 'List staff.' },
        { method: 'POST', path: '/api/staff', auth: true, group: 'Admin Setup', description: 'Create/update staff.' },
        { method: 'DELETE', path: '/api/staff/:id', auth: true, group: 'Admin Setup', description: 'Delete staff.' },
        { method: 'GET', path: '/api/permissions', auth: false, group: 'Admin Setup', description: 'Role permissions.' },
        { method: 'POST', path: '/api/permissions', auth: false, group: 'Admin Setup', description: 'Save role permissions.' },
        { method: 'GET', path: '/api/designation-permissions', auth: true, group: 'Admin Setup', description: 'Designation/action permissions.' },
        { method: 'POST', path: '/api/designation-permissions', auth: true, group: 'Admin Setup', description: 'Save designation/action permissions.' },
        { method: 'GET', path: '/api/admin-credentials', auth: false, group: 'Admin Setup', description: 'Admin credential status.' },
        { method: 'POST', path: '/api/admin-credentials', auth: false, group: 'Admin Setup', description: 'Update admin credentials.' },

        { method: 'GET', path: '/api/banners', auth: false, group: 'Website and Facilities', description: 'Banners for website and portals.' },
        { method: 'POST', path: '/api/banners', auth: false, group: 'Website and Facilities', description: 'Save banner.' },
        { method: 'DELETE', path: '/api/banners/:id', auth: false, group: 'Website and Facilities', description: 'Delete banner.' },
        { method: 'GET', path: '/api/ads', auth: false, group: 'Website and Facilities', description: 'Ads for student and teacher portals.' },
        { method: 'POST', path: '/api/ads', auth: false, group: 'Website and Facilities', description: 'Save portal ad.' },
        { method: 'DELETE', path: '/api/ads/:id', auth: false, group: 'Website and Facilities', description: 'Delete portal ad.' },
        { method: 'GET', path: '/api/online-admissions', auth: false, group: 'Website and Facilities', description: 'List website online admission applications.' },
        { method: 'POST', path: '/api/online-admissions', auth: false, group: 'Website and Facilities', description: 'Submit or save an online admission application.' },
        { method: 'POST', path: '/api/online-admissions/:id', auth: false, group: 'Website and Facilities', description: 'Update online admission application status/details.' },
        { method: 'DELETE', path: '/api/online-admissions/:id', auth: false, group: 'Website and Facilities', description: 'Delete online admission application.' },
        { method: 'GET', path: '/api/library/issues', auth: false, group: 'Website and Facilities', description: 'Library issue records.' },
        { method: 'POST', path: '/api/library/issues', auth: false, group: 'Website and Facilities', description: 'Save library issue.' },
        { method: 'POST', path: '/api/library/issues/:id/return', auth: false, group: 'Website and Facilities', description: 'Mark book returned.' },
        { method: 'DELETE', path: '/api/library/issues/:id', auth: false, group: 'Website and Facilities', description: 'Delete library issue.' },
        { method: 'GET', path: '/api/cafe/contracts', auth: false, group: 'Website and Facilities', description: 'Cafe contracts.' },
        { method: 'POST', path: '/api/cafe/contracts', auth: false, group: 'Website and Facilities', description: 'Save cafe contract.' },
        { method: 'DELETE', path: '/api/cafe/contracts/:id', auth: false, group: 'Website and Facilities', description: 'Delete cafe contract.' },
        { method: 'GET', path: '/api/transport/assignments', auth: false, group: 'Website and Facilities', description: 'Transport assignments.' },
        { method: 'POST', path: '/api/transport/assignments', auth: false, group: 'Website and Facilities', description: 'Save transport assignment.' },
        { method: 'DELETE', path: '/api/transport/assignments/:id', auth: false, group: 'Website and Facilities', description: 'Delete transport assignment.' },

        { method: 'GET', path: '/api/email/config', auth: true, group: 'Utilities', description: 'SMTP config status.' },
        { method: 'POST', path: '/api/email/send', auth: true, group: 'Utilities', description: 'Send email.' },
        { method: 'POST', path: '/api/ai-chat', auth: true, group: 'Utilities', description: 'AI chat with school context.' },
        { method: 'GET', path: '/api/catalog', auth: false, group: 'Developer', description: 'Machine-readable API catalog.' },
        { method: 'GET', path: '/api/mobile-api-list', auth: false, group: 'Developer', description: 'Alias for API catalog.' }
    ]
};

module.exports = apiCatalog;
